"""apply_audit_mixin_and_h3

Revision ID: bf8330f6987f
Revises: d53862026f14
Create Date: 2026-03-11 23:55:27.833309

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bf8330f6987f"
down_revision: str | Sequence[str] | None = "d53862026f14"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("grid_cells", sa.Column("h3_index", sa.String(), nullable=False))
    op.add_column(
        "grid_cells",
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.add_column(
        "grid_cells",
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index(op.f("ix_grid_cells_h3_index"), "grid_cells", ["h3_index"], unique=True)
    op.drop_column("grid_cells", "center_lat")
    op.drop_column("grid_cells", "center_lon")
    op.drop_column("grid_cells", "grid_reference")
    op.add_column(
        "grid_metrics",
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.add_column(
        "grid_metrics",
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.add_column(
        "map_granularities",
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.add_column(
        "map_granularities",
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.alter_column(
        "profiles", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
    )
    op.add_column(
        "raw_transactions",
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.add_column(
        "raw_transactions",
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.alter_column(
        "search_properties",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "searches", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
    )

    # Grant permissions to make tables visible in Supabase Studio/API
    op.execute("GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;")
    op.execute(
        "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;"
    )
    op.execute(
        "GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;"
    )
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;"
    )
    op.execute(
        "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "searches", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
    )
    op.alter_column(
        "search_properties",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_column("raw_transactions", "updated_at")
    op.drop_column("raw_transactions", "created_at")
    op.alter_column(
        "profiles", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
    )
    op.drop_column("map_granularities", "updated_at")
    op.drop_column("map_granularities", "created_at")
    op.drop_column("grid_metrics", "updated_at")
    op.drop_column("grid_metrics", "created_at")
    op.add_column(
        "grid_cells", sa.Column("grid_reference", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "grid_cells",
        sa.Column(
            "center_lon", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "grid_cells",
        sa.Column(
            "center_lat", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_grid_cells_h3_index"), table_name="grid_cells")
    op.drop_column("grid_cells", "updated_at")
    op.drop_column("grid_cells", "created_at")
    op.drop_column("grid_cells", "h3_index")
    # ### end Alembic commands ###
