"""refactor_architecture_and_dvf

Revision ID: d53862026f14
Revises:
Create Date: 2026-03-11 23:06:33.445271

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d53862026f14"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    op.create_table(
        "grid_cells",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("grid_reference", sa.Integer(), nullable=True),
        sa.Column("resolution", sa.Integer(), nullable=False),
        sa.Column("center_lat", sa.Float(), nullable=False),
        sa.Column("center_lon", sa.Float(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Index is automatically created by GeoAlchemy2
    # op.create_index('idx_grid_cells_geometry', 'grid_cells', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table(
        "grid_metrics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("grid_cell_id", sa.UUID(), nullable=False),
        sa.Column("granularity", sa.String(length=50), nullable=False),
        sa.Column("period", sa.String(length=50), nullable=False),
        sa.Column("price_per_sqm", sa.Float(), nullable=True),
        sa.Column("evolution_pct", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["grid_cell_id"], ["grid_cells.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_period_fast_search", "grid_metrics", ["period"], unique=False)
    op.create_index(
        "idx_unique_metric", "grid_metrics", ["grid_cell_id", "granularity", "period"], unique=True
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("contact_email", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "searches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("epicenter_lat", sa.Float(), nullable=False),
        sa.Column("epicenter_lon", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "search_properties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("search_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "type", sa.Enum("appartement", "maison", name="propertytypeenum"), nullable=False
        ),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("surface", sa.Float(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("price_per_sqm", sa.Float(), nullable=True),
        sa.Column("agency_name", sa.String(), nullable=True),
        sa.Column("annual_charges", sa.Float(), nullable=True),
        sa.Column("energy_costs", sa.Float(), nullable=True),
        sa.Column("property_tax", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["search_id"], ["searches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "map_granularities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("resolution_value", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resolution_value"),
    )
    op.create_table(
        "raw_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("id_mutation", sa.String(), nullable=True),
        sa.Column("date_mutation", sa.Date(), nullable=True),
        sa.Column("numero_disposition", sa.String(), nullable=True),
        sa.Column("nature_mutation", sa.String(), nullable=True),
        sa.Column("valeur_fonciere", sa.Float(), nullable=True),
        sa.Column("adresse_numero", sa.String(), nullable=True),
        sa.Column("adresse_suffixe", sa.String(), nullable=True),
        sa.Column("adresse_nom_voie", sa.String(), nullable=True),
        sa.Column("adresse_code_voie", sa.String(), nullable=True),
        sa.Column("code_postal", sa.String(), nullable=True),
        sa.Column("code_commune", sa.String(), nullable=True),
        sa.Column("nom_commune", sa.String(), nullable=True),
        sa.Column("code_departement", sa.String(), nullable=True),
        sa.Column("ancien_code_commune", sa.String(), nullable=True),
        sa.Column("ancien_nom_commune", sa.String(), nullable=True),
        sa.Column("id_parcelle", sa.String(), nullable=True),
        sa.Column("ancien_id_parcelle", sa.String(), nullable=True),
        sa.Column("numero_volume", sa.String(), nullable=True),
        sa.Column("lot1_numero", sa.String(), nullable=True),
        sa.Column("lot1_surface_carrez", sa.Float(), nullable=True),
        sa.Column("lot2_numero", sa.String(), nullable=True),
        sa.Column("lot2_surface_carrez", sa.Float(), nullable=True),
        sa.Column("lot3_numero", sa.String(), nullable=True),
        sa.Column("lot3_surface_carrez", sa.Float(), nullable=True),
        sa.Column("lot4_numero", sa.String(), nullable=True),
        sa.Column("lot4_surface_carrez", sa.Float(), nullable=True),
        sa.Column("lot5_numero", sa.String(), nullable=True),
        sa.Column("lot5_surface_carrez", sa.Float(), nullable=True),
        sa.Column("nombre_lots", sa.Integer(), nullable=True),
        sa.Column("code_type_local", sa.String(), nullable=True),
        sa.Column("type_local", sa.String(), nullable=True),
        sa.Column("surface_reelle_bati", sa.Float(), nullable=True),
        sa.Column("nombre_pieces_principales", sa.Integer(), nullable=True),
        sa.Column("code_nature_culture", sa.String(), nullable=True),
        sa.Column("nature_culture", sa.String(), nullable=True),
        sa.Column("code_nature_culture_speciale", sa.String(), nullable=True),
        sa.Column("nature_culture_speciale", sa.String(), nullable=True),
        sa.Column("surface_terrain", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_raw_gps", "raw_transactions", ["latitude", "longitude"], unique=False)
    op.create_index("idx_raw_mutation", "raw_transactions", ["id_mutation"], unique=False)

    # Custom SQL for Supabase Auth trigger
    op.execute("""
    create or replace function public.handle_new_user()
    returns trigger as $$
    begin
      insert into public.profiles (id, first_name, last_name, contact_email, created_at)
      values (new.id, new.raw_user_meta_data->>'first_name', new.raw_user_meta_data->>'last_name', new.email, now());
      return new;
    end;
    $$ language plpgsql security definer;
    """)
    op.execute("drop trigger if exists on_auth_user_created on auth.users;")
    op.execute("""
    create trigger on_auth_user_created
      after insert on auth.users
      for each row execute procedure public.handle_new_user();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_raw_mutation", table_name="raw_transactions")
    op.drop_index("idx_raw_gps", table_name="raw_transactions")
    op.drop_table("raw_transactions")
    op.drop_table("map_granularities")
    op.drop_table("search_properties")
    op.drop_table("searches")
    op.drop_table("profiles")
    op.drop_index("idx_unique_metric", table_name="grid_metrics")
    op.drop_index("idx_period_fast_search", table_name="grid_metrics")
    op.drop_table("grid_metrics")
    op.drop_index("idx_grid_cells_geometry", table_name="grid_cells", postgresql_using="gist")
    op.drop_table("grid_cells")

    # Custom SQL to remove Supabase Auth trigger
    op.execute("drop trigger if exists on_auth_user_created on auth.users;")
    op.execute("drop function if exists public.handle_new_user();")
    # ### end Alembic commands ###
